/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

/**
 *
 * @author Mike
 */
public class VentanaDivisas extends javax.swing.JFrame {

    private double valorDolar = 17.01;
    private double valorEuro = 18.62;
    private double valorLibra = 21.64;
    private double valorYen = 0.1171;
    private double valorWon = 0.01278;
    private String salida1;
    private String salida2;

    /**
     * Creates new form VentanaDivisas
     */
    public VentanaDivisas() {
        //setSize(500, 300);
        initComponents();
        setLocationRelativeTo(null);
        campoMoneda1.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaFunciones = new javax.swing.JLabel();
        comboFunciones = new javax.swing.JComboBox<>();
        campoMoneda1 = new javax.swing.JTextField();
        comboMoneda1 = new javax.swing.JComboBox<>();
        campoMoneda2 = new javax.swing.JTextField();
        comboMoneda2 = new javax.swing.JComboBox<>();
        etiquetaSalida1 = new javax.swing.JLabel();
        etiquetaSalida2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        etiquetaMoneda2 = new javax.swing.JLabel();
        etiquetaMoneda1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Divisas");
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        panel.setPreferredSize(new java.awt.Dimension(500, 300));

        etiquetaFunciones.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        etiquetaFunciones.setText("Seleccione tipo de conversor");

        comboFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Divisas", "Temperatura" }));
        comboFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFuncionesActionPerformed(evt);
            }
        });

        campoMoneda1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoMoneda1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoMoneda1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMoneda1FocusLost(evt);
            }
        });
        campoMoneda1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoMoneda1InputMethodTextChanged(evt);
            }
        });
        campoMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMoneda1ActionPerformed(evt);
            }
        });

        comboMoneda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Euro", "Libra Esterlina", "Yen Japonés", "Won sul-coreano" }));
        comboMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMoneda1ActionPerformed(evt);
            }
        });

        campoMoneda2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campoMoneda2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoMoneda2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoMoneda2FocusGained(evt);
            }
        });
        campoMoneda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMoneda2ActionPerformed(evt);
            }
        });

        comboMoneda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Euro", "Libra Esterlina", "Yen Japonés", "Won sul-coreano" }));
        comboMoneda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMoneda2ActionPerformed(evt);
            }
        });

        etiquetaSalida1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaSalida1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaSalida1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        etiquetaSalida2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaSalida2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaSalida2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cambio-de-divisas.png"))); // NOI18N

        etiquetaMoneda2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        etiquetaMoneda2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaMoneda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaD.png"))); // NOI18N
        etiquetaMoneda2.setText("Mx");
        etiquetaMoneda2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        etiquetaMoneda1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        etiquetaMoneda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaD.png"))); // NOI18N
        etiquetaMoneda1.setText("Mx");
        etiquetaMoneda1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        etiquetaMoneda1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMoneda1, 0, 108, Short.MAX_VALUE)
                            .addComponent(campoMoneda2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(etiquetaMoneda1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(etiquetaMoneda2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaSalida1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(etiquetaSalida2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo)
                            .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaFunciones))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(etiquetaFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo)
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaMoneda1))
                    .addComponent(etiquetaSalida1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaSalida2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaMoneda2)
                        .addComponent(comboMoneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMoneda1ActionPerformed
        // TODO add your handling code here:
        convertirMoneda1();
    }//GEN-LAST:event_campoMoneda1ActionPerformed

    private void comboMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMoneda1ActionPerformed
        // TODO add your handling code here:
        campoMoneda1.requestFocus();
    }//GEN-LAST:event_comboMoneda1ActionPerformed

    private void campoMoneda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMoneda2ActionPerformed
        // TODO add your handling code here:
        convertirMoneda2();
    }//GEN-LAST:event_campoMoneda2ActionPerformed

    private void comboFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFuncionesActionPerformed
        // TODO add your handling code here:
        if (comboFunciones.getSelectedItem().equals("Temperatura")) {
            VentanaTemperatura temperatura = new VentanaTemperatura();
            temperatura.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_comboFuncionesActionPerformed

    private void campoMoneda1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoMoneda1InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoMoneda1InputMethodTextChanged

    private void campoMoneda1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMoneda1FocusLost
        // TODO add your handling code here:
        //prueba();
        
    }//GEN-LAST:event_campoMoneda1FocusLost

    private void campoMoneda1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMoneda1FocusGained
        // TODO add your handling code here:
        if(!campoMoneda1.getText().isBlank()) {
            convertirMoneda1();
        }
    }//GEN-LAST:event_campoMoneda1FocusGained

    private void comboMoneda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMoneda2ActionPerformed
        // TODO add your handling code here:
        campoMoneda2.requestFocus();
    }//GEN-LAST:event_comboMoneda2ActionPerformed

    private void campoMoneda2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMoneda2FocusGained
        // TODO add your handling code here:
        if(!campoMoneda2.getText().isBlank()) {
            convertirMoneda2();
        }
    }//GEN-LAST:event_campoMoneda2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisas().setVisible(true);
            }
        });
    }

    public void convertirMoneda1() {
        String entrada = campoMoneda1.getText();
        try {

            if (comboMoneda1.getSelectedItem().equals("Dólar")) {
                salida1 = String.format("%.3f", (valorDolar * Double.parseDouble(entrada)));
                etiquetaSalida1.setText(salida1 + " Mx");
            } else if (comboMoneda1.getSelectedItem().equals("Euro")) {
                salida1 = String.format("%.3f", (valorEuro * Double.parseDouble(entrada)));
                etiquetaSalida1.setText(salida1 + " Mx");
            } else if (comboMoneda1.getSelectedItem().equals("Libra Esterlina")) {
                salida1 = String.format("%.3f", (valorLibra * Double.parseDouble(entrada)));
                etiquetaSalida1.setText(salida1 + " Mx");
            } else if (comboMoneda1.getSelectedItem().equals("Yen Japonés")) {
                salida1 = String.format("%.3f", (valorYen * Double.parseDouble(entrada)));
                etiquetaSalida1.setText(salida1 + " Mx");
            } else if (comboMoneda1.getSelectedItem().equals("Won sul-coreano")) {
                salida1 = String.format("%.3f", (valorWon * Double.parseDouble(entrada)));
                etiquetaSalida1.setText(salida1 + " Mx");
            }
        } catch (Exception e) {
             if (campoMoneda1.getText().isBlank()) {
                etiquetaSalida1.setText("Campo vacío");
            } else {
                etiquetaSalida1.setText("Ingresa Valor válido");
            }
        }
        
    }
    public void convertirMoneda2() {
        String entrada2 = campoMoneda2.getText();
        try {
            if (comboMoneda2.getSelectedItem().equals("Dólar")) {
                salida2 = String.format("%.3f", (Double.parseDouble(entrada2) / valorDolar));
                etiquetaSalida2.setText(salida2 + " Dlls");
            } else if (comboMoneda2.getSelectedItem().equals("Euro")) {
                salida2 = String.format("%.3f", (Double.parseDouble(entrada2) / valorEuro));
                etiquetaSalida2.setText(salida2 + " €");
            } else if (comboMoneda2.getSelectedItem().equals("Libra Esterlina")) {
                salida2 = String.format("%.3f", (Double.parseDouble(entrada2) / valorLibra));
                etiquetaSalida2.setText(salida2 + "  £");
            } else if (comboMoneda2.getSelectedItem().equals("Yen Japonés")) {
                salida2 = String.format("%.3f", (Double.parseDouble(entrada2) / valorYen));
                etiquetaSalida2.setText(salida2 + " ¥");
            } else if (comboMoneda2.getSelectedItem().equals("Won sul-coreano")) {
                salida2 = String.format("%.3f", (Double.parseDouble(entrada2) / valorWon));
                etiquetaSalida2.setText(salida2 + "  W");
            }
        } catch (Exception e) {

            if (campoMoneda2.getText().isBlank()) {
                etiquetaSalida2.setText("Campo vacío");
            } else {
                etiquetaSalida2.setText("Ingresa Valor válido");
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoMoneda1;
    private javax.swing.JTextField campoMoneda2;
    private javax.swing.JComboBox<String> comboFunciones;
    private javax.swing.JComboBox<String> comboMoneda1;
    private javax.swing.JComboBox<String> comboMoneda2;
    private javax.swing.JLabel etiquetaFunciones;
    private javax.swing.JLabel etiquetaMoneda1;
    private javax.swing.JLabel etiquetaMoneda2;
    private javax.swing.JLabel etiquetaSalida1;
    private javax.swing.JLabel etiquetaSalida2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
