/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import javax.swing.ImageIcon;

/**
 *
 * @author Mike
 */
public class VentanaTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTemperatura
     */
    public VentanaTemperatura() {
        //setSize(500, 300);
        initComponents();
        setLocationRelativeTo(null);
        //comboTemp1.setSelectedIndex(0);
        campoTemp1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaFunciones = new javax.swing.JLabel();
        comboFunciones = new javax.swing.JComboBox<>();
        logoTemperatura = new javax.swing.JLabel();
        comboTemp1 = new javax.swing.JComboBox<>();
        campoTemp1 = new javax.swing.JTextField();
        etiquetaSalida1 = new javax.swing.JLabel();
        campoTemp2 = new javax.swing.JTextField();
        comboTemp2 = new javax.swing.JComboBox<>();
        etiquetaSalida2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Temperatura");
        setResizable(false);

        etiquetaFunciones.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        etiquetaFunciones.setText("Seleccione tipo de conversor");

        comboFunciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperatura", "Divisas" }));
        comboFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFuncionesActionPerformed(evt);
            }
        });

        logoTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/termometro (1).png"))); // NOI18N

        comboTemp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Kelvin" }));
        comboTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemp1ActionPerformed(evt);
            }
        });

        campoTemp1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        campoTemp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTemp1FocusGained(evt);
            }
        });
        campoTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTemp1ActionPerformed(evt);
            }
        });

        etiquetaSalida1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaSalida1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaSalida1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        campoTemp2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        campoTemp2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoTemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTemp2ActionPerformed(evt);
            }
        });

        comboTemp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Kelvin" }));
        comboTemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTemp2ActionPerformed(evt);
            }
        });

        etiquetaSalida2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        etiquetaSalida2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaD.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/termometroC.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaD.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/termometroC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoTemperatura)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboTemp1, 0, 105, Short.MAX_VALUE)
                            .addComponent(campoTemp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaSalida2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaFunciones)
                    .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaFunciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoTemperatura)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(campoTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(etiquetaSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaSalida2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoTemp2)
                                .addComponent(comboTemp2)))
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemp1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("kelvin.png");
//        if (comboTemp1.getSelectedItem().equals("Kelvin")) {
//            etiquetaTemp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelvin.png")));
//        } else {
//            etiquetaTemp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grados-fahrenheit.png")));
//        }
        campoTemp1.requestFocus();
    }//GEN-LAST:event_comboTemp1ActionPerformed

    private void campoTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTemp1ActionPerformed
        // TODO add your handling code here:
        convertirTemperatura1();
    }//GEN-LAST:event_campoTemp1ActionPerformed

    private void campoTemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTemp2ActionPerformed
        // TODO add your handling code here:
        convertirTemperatura2();
    }//GEN-LAST:event_campoTemp2ActionPerformed

    private void comboFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFuncionesActionPerformed
        // TODO add your handling code here:
        if (comboFunciones.getSelectedItem().equals("Divisas")) {
            VentanaDivisas divisas = new VentanaDivisas();
            divisas.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_comboFuncionesActionPerformed

    private void comboTemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTemp2ActionPerformed
        // TODO add your handling code here:
        convertirTemperatura2();
    }//GEN-LAST:event_comboTemp2ActionPerformed

    private void campoTemp1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTemp1FocusGained
        // TODO add your handling code here:
        if(!campoTemp1.getText().isEmpty()) {
            convertirTemperatura1();
        }
    }//GEN-LAST:event_campoTemp1FocusGained

    private void convertirTemperatura1() {
        String entrada;
        String salida;
        try {
            if (comboTemp1.getSelectedIndex() == 0) {
                entrada = campoTemp1.getText();
                salida = String.format("%.3f", ((Double.parseDouble(entrada) - 32)) * 5 / 9);
                etiquetaSalida1.setText(salida + " °C");
                //unidadSalida.setText("°F");
            } else if (comboTemp1.getSelectedItem().equals("Kelvin")) {
                entrada = campoTemp1.getText();
                salida = String.format("%.3f", (Double.parseDouble(entrada)) - 273.15);
                etiquetaSalida1.setText(salida + " °C");
                //unidadSalida.setText("°K");
            }

        } catch (Exception e) {
            etiquetaSalida1.setText("Ingrese un valor");
        }
    }

    private void convertirTemperatura2() {
        String entrada;
        String salida;
        try {
            if (comboTemp2.getSelectedIndex() == 0) {
                entrada = campoTemp2.getText();
                salida = String.format("%.3f", (Double.parseDouble(entrada) * (9 / 5)) + 32);
                etiquetaSalida2.setText(salida + " °F");
                //unidadSalida.setText("°F");
            } else if (comboTemp2.getSelectedItem().equals("Kelvin")) {
                entrada = campoTemp2.getText();
                salida = String.format("%.3f", (Double.parseDouble(entrada)) + 273.15);
                etiquetaSalida2.setText(salida + " °K");
                //unidadSalida.setText("°K");
            }
        } catch (Exception e) {
            etiquetaSalida2.setText("Ingrese un valor");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTemp1;
    private javax.swing.JTextField campoTemp2;
    private javax.swing.JComboBox<String> comboFunciones;
    private javax.swing.JComboBox<String> comboTemp1;
    private javax.swing.JComboBox<String> comboTemp2;
    private javax.swing.JLabel etiquetaFunciones;
    private javax.swing.JLabel etiquetaSalida1;
    private javax.swing.JLabel etiquetaSalida2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoTemperatura;
    // End of variables declaration//GEN-END:variables
}
